on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Build and create artifact
        run: |
          ./build.sh
          du -sh out/*
          echo current-dir
          ls
          echo output
          ls out
          echo zipp-files
          zip -r linuxpdf.zip out

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linuxpdf.zip
          path: linuxpdf.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: linuxpdf.zip

      - name: Deploy
        run: |
          # Add your deploy steps here
